//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： cwx99
//             Created Time： 2011/11/11 13:00:41
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class Entity分钟线表 : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>证券代码</summary>
        public const string @__证券代码 = "证券代码";
        
        /// <summary>证券名称</summary>
        public const string @__证券名称 = "证券名称";
        
        /// <summary>成交时间</summary>
        public const string @__成交时间 = "成交时间";
        
        /// <summary>最新</summary>
        public const string @__最新 = "最新";
        
        /// <summary>成交量</summary>
        public const string @__成交量 = "成交量";
        
        /// <summary>成交额</summary>
        public const string @__成交额 = "成交额";
        
        private int m_ID;
        
        private string m_证券代码;
        
        private string m_证券名称;
        
        private System.DateTime m_成交时间 = DateTime.MinValue;
        
        private decimal m_最新;
        
        private int m_成交量;
        
        private decimal m_成交额;
        
        /// <summary>构造函数</summary>
        public Entity分钟线表()
        {
        }
        
        /// <summary>属性ID </summary>
        public int ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性证券代码 </summary>
        public string 证券代码
        {
            get
            {
                return this.m_证券代码;
            }
            set
            {
                this.m_证券代码 = value;
            }
        }
        
        /// <summary>属性证券名称 </summary>
        public string 证券名称
        {
            get
            {
                return this.m_证券名称;
            }
            set
            {
                this.m_证券名称 = value;
            }
        }
        
        /// <summary>属性成交时间 </summary>
        public System.DateTime 成交时间
        {
            get
            {
                return this.m_成交时间;
            }
            set
            {
                this.m_成交时间 = value;
            }
        }
        
        /// <summary>属性最新 </summary>
        public decimal 最新
        {
            get
            {
                return this.m_最新;
            }
            set
            {
                this.m_最新 = value;
            }
        }
        
        /// <summary>属性成交量 </summary>
        public int 成交量
        {
            get
            {
                return this.m_成交量;
            }
            set
            {
                this.m_成交量 = value;
            }
        }
        
        /// <summary>属性成交额 </summary>
        public decimal 成交额
        {
            get
            {
                return this.m_成交额;
            }
            set
            {
                this.m_成交额 = value;
            }
        }
    }
    
    /// Entity分钟线表执行类
    public abstract class Entity分钟线表Action
    {
        
        private Entity分钟线表Action()
        {
        }
        
        public static void Save(Entity分钟线表 obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static Entity分钟线表 RetrieveAEntity分钟线表(int ID)
        {
            Entity分钟线表 obj=new Entity分钟线表();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveEntity分钟线表()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(Entity分钟线表));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetEntity分钟线表()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(Entity分钟线表));
            return rc.AsDataTable();
        }
    }
}
