//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： cwx99
//             Created Time： 2011/11/15 21:47:32
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class Entity系统选项表 : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>关键字</summary>
        public const string @__关键字 = "关键字";
        
        /// <summary>值</summary>
        public const string @__值 = "值";
        
        /// <summary>说明</summary>
        public const string @__说明 = "说明";
        
        private int m_ID;
        
        private string m_关键字;
        
        private string m_值;
        
        private string m_说明;
        
        /// <summary>构造函数</summary>
        public Entity系统选项表()
        {
        }
        
        /// <summary>属性ID </summary>
        public int ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性关键字 </summary>
        public string 关键字
        {
            get
            {
                return this.m_关键字;
            }
            set
            {
                this.m_关键字 = value;
            }
        }
        
        /// <summary>属性值 </summary>
        public string 值
        {
            get
            {
                return this.m_值;
            }
            set
            {
                this.m_值 = value;
            }
        }
        
        /// <summary>属性说明 </summary>
        public string 说明
        {
            get
            {
                return this.m_说明;
            }
            set
            {
                this.m_说明 = value;
            }
        }
    }
    
    /// Entity系统选项表执行类
    public abstract class Entity系统选项表Action
    {
        
        private Entity系统选项表Action()
        {
        }
        
        public static void Save(Entity系统选项表 obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static Entity系统选项表 RetrieveAEntity系统选项表(int ID)
        {
            Entity系统选项表 obj=new Entity系统选项表();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveEntity系统选项表()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(Entity系统选项表));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetEntity系统选项表()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(Entity系统选项表));
            return rc.AsDataTable();
        }
    }
}
