//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： cwx99
//             Created Time： 2011/11/8 11:49:00
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class Entity代码表 : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>证券代码</summary>
        public const string @__证券代码 = "证券代码";
        
        /// <summary>证券名称</summary>
        public const string @__证券名称 = "证券名称";
        
        /// <summary>速记码</summary>
        public const string @__速记码 = "速记码";
        
        private int m_ID;
        
        private string m_证券代码;
        
        private string m_证券名称;
        
        private string m_速记码;
        
        /// <summary>构造函数</summary>
        public Entity代码表()
        {
        }
        
        /// <summary>属性ID </summary>
        public int ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性证券代码 </summary>
        public string 证券代码
        {
            get
            {
                return this.m_证券代码;
            }
            set
            {
                this.m_证券代码 = value;
            }
        }
        
        /// <summary>属性证券名称 </summary>
        public string 证券名称
        {
            get
            {
                return this.m_证券名称;
            }
            set
            {
                this.m_证券名称 = value;
            }
        }
        
        /// <summary>属性速记码 </summary>
        public string 速记码
        {
            get
            {
                return this.m_速记码;
            }
            set
            {
                this.m_速记码 = value;
            }
        }
    }
    
    /// Entity代码表执行类
    public abstract class Entity代码表Action
    {
        
        private Entity代码表Action()
        {
        }
        
        public static void Save(Entity代码表 obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static Entity代码表 RetrieveAEntity代码表(int ID)
        {
            Entity代码表 obj=new Entity代码表();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveEntity代码表()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(Entity代码表));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetEntity代码表()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(Entity代码表));
            return rc.AsDataTable();
        }
    }
}
